### ISSUE TITLE
Add new task = add new person

### ISSUE THREAD

**Issue by gperu** [carpentries/amy#1730] opened 2020-10-26 11:55 UTC
When a person is not in the DB, when adding this person as a role in a workshop, we (admins) need to switch to another tab, open the 'new person' form, add the person and then go back to the workshop and associate a role with that person. This had sense when, in the past, we had the ambition of creating persons with a lot of other useful details. This ambition has been, I guess, hindered by reality (lack of time) and privacy considerations. 

It would be excellent, if we still want to associate names with roles, if the new person could be added to the DB from the 'add task' box in the workshops. 

What do you, @sheraaronhurt and Aleks Nenadic think?

Thank you for submitting this issue to AMY.  If this represents an urgent problem such as AMY not loading at all, please contact team@carpentries.org so we can respond promptly.

Non-urgent issues will be reviewed weekly by @maneesha.  She will follow up here with you and/or other team members if more information is needed. Issues will be prioritized, considering whether they identify broken features, identify potential enhancements to existing features, or request implemention of entirely new features.

After prioritizing, one of the following will happen:

* High priority issues will be included in an upcoming work cycle and labeled for an existing milestone.
* Medium to low priority issues will be considered for a future work cycle and labeled "later."  These will be re-reviewed periodically to consider them for an upcoming work cycle. 
* Issues that are stale, redundant, or are otherwise assessed not to positively impact user workflows will be closed and labeled "wont-fix"

Comments in the issue itself will provide further context. Please contact team@carpentries.org with any questions.  Thank you again for your contribution and helping us improve AMY.

**Comment by maneesha** [comment] 2020-10-26 14:53
Closing as a duplicate of #1564

**Closed by maneesha** 2020-10-26 14:53 UTC
