### ISSUE TITLE
Filtering trainees who are at the end of their time

### ISSUE THREAD

**Issue by chrismedrela** [carpentries/amy#1149] opened 2017-02-13 17:03 UTC

**Comment by maneesha** [comment] 2019-06-24 21:37
I think this was intended to give us a report of everyone who has not completed certification requirements and the three month deadline is approaching.

Some questions for @ErinBecker  or @karenword  to help build this report:

1.  Is it three months or 90 days?  *Seems like a minor point from our end, but we will have to code something*
2.  Is it three months from the first day or the last day of the training event?  *Also a minor point for our two day events, but will become significant if we consider events over a longer span, so I would suggest last day.* 
3. How far in the future do you want to  get deadlines?  For example, "Return everyone whose deadline is between TODAY + 30 days to TODAY + 45 days" run on June 24 would return everyone whose deadline is between July 24 and August 8.  Do you you want this fixed or variable? (meaning the user could select the dates in the range)
4.  What do you want the query to return?  I'm thinking name, email, training event date, steps completed to checkout, checkout deadline.
5. Do you want to see the email content pre-populated? (so when you click on the "mail selected people" it opens an email in your email client.  This requires you to have set up a default email client with your browser.
6. Are you also interested in tracking extensions? If so I can open a new issue about that.

**Comment by maneesha** [comment] 2019-06-24 21:38
@ErinBecker  and @karenword  Let me know how much of a priority you see this.  Based on this I'll follow up with the questions above.

**Which of the following applies to when you want to see this fixed?**
1. Would like to see this fixed as soon as possible, in the next 1-2 development cycles (i.e., by September 2019)
2. Would like to see this fixed later (by the end of 2019)
3. Would like to see this fixed, but possibly as part of a larger project that needs more planning
4. Not sure
5. No longer relevant - OK to close

**Comment by karenword** [comment] 2019-06-25 16:49
I'll defer to @ErinBecker on this one because it has more to do with checkout management than training.

**Comment by ErinBecker** [comment] 2019-07-05 21:56
3 - I'd like to see this included in the broader conversation around AMY automation and streamlining for workshops and instructor training. @sheraaronhurt @Talishask have been handling the reminder email, so let's make sure they're involved in this conversation.

**Comment by Talishask** [comment] 2019-07-06 15:07
Agreed 3

**Comment by maneesha** [comment] 2022-04-22 13:58
We do have automated emails going out to trainees now, so I am closing this here

**Closed by maneesha** 2022-04-22 13:58 UTC
Labels: type: enhancement
