### ISSUE TITLE
BUG: Handling conflict with semester long workshops

### ISSUE THREAD

**Issue by annajiat** [carpentries/amy#2253] opened 2022-10-25 13:46 UTC
I am teaching some semester long workshops.

For all workshops including non-conflicting ones, it shows
"You cannot apply for this workshop. You are teaching at a conflicting workshop: 2022-08-22-ashesiu-ds-hybrid."
because the start and end dates overlap. To correctly identify conflicts, we might need to check time conflicts, not just date overlaps.

a) Would it be possible to allow users to ignore / turn OFF certain errors like conflicting with semester long ones?

b) In case of instructor shortages, sometimes we had to teach different parts of conflicting workshops. Should we have a filter and configuration to handle this? Or somehow notify administrator that in case of urgencies, some instructors can indicate preference to be contacted for conflicting workshops, if they willingly would like to take the load of balancing between the conflicting ones.

**Comment by maneesha** [comment] 2022-10-28 10:31
This is a feature, not a bug. Most workshops run a few days and we do not want to have people signing up for workshops on the same day. I'm closing this here as it is being addressed with #2256

**Closed by maneesha** 2022-10-28 10:31 UTC
