### ISSUE TITLE
Re-label fields in view to assign roles

### ISSUE THREAD

**Issue by maneesha** [carpentries/amy#2222] opened 2022-09-12 19:57 UTC
In the view to assign roles, we should have some fields re-labeled to make them easier for the user to understand.

Config --> Role Name
Award --> Associated Award
Start --> Role Start Date
End  --> Role End Date
Inactivation --> Reason for inactivation
Membership --> Associated Membership

I am not sure what the last three fields (URL, Generic relation object type, Generic relation object) are supposed to be.  @pbanaszkiewicz  Can you clarify? 

![image](https://user-images.githubusercontent.com/829690/189743655-67d81817-92ee-4af6-8343-75dcf098d7fd.png)

**Comment by pbanaszkiewicz** [comment] 2022-09-15 15:56
@maneesha 
1. URL is a field for storing arbitrary URL related to a community role. I think it was designed to link to a repository, which person was maintaining, but it doesn't have any specific validation (except for generic URL format). When "Should allow for additional URL?" is not checked in the community role config, then URL field in the community role must be empty.
2. "Generic relation object" field is intended to link to any object in AMY with a type selected in "Generic relation object type" field. These fields are only available if the community role config has selected "Generic relation content type". For example Maintainer role has "Generic relation content type" set to "Lesson". This setting makes community role fields display a list of lessons. (You can test this in AMY yourself when you assign a maintainer role to anyone).

**Comment by maneesha** [comment] 2022-09-15 20:02
I see - thank you!
I will talk with our team to see how we want to label these fields.  For now, we can proceed with the changes noted above.

**Closed** 2022-09-16 13:39 UTC
Labels: priority: essential, Getting started
