### ISSUE TITLE
Contact field for workshops is a list now (rather than a single value)

### ISSUE THREAD

**Issue by anenadic** [carpentries/amy#1191] opened 2017-05-23 08:59 UTC
Contact field for workshops is a list now (rather than a single value) in workshop template so this needs to be supported in AMY too. Values get concatenated without a space, a comma or other separator when updating workshop data from a URL. For example see workshop with slug: 2017-06-21-qmul.

**Comment by chrismedrela** [comment] 2017-07-10 14:53
The cause of the problem is in the workshop template, not AMY. When generating `<meta>` tags, the template still assumes that `contact` is a single value rather than a list: [see the template](https://github.com/swcarpentry/workshop-template/blob/gh-pages/_layouts/workshop.html#L19). So the values get concatenated by jekyll, not AMY. Have a look at the source code of [the mentioned workshop](https://anenadic.github.io/2017-06-21-qmul/) and you can see:
```html
<meta name="contact" content="rebecca.stewart@qmul.ac.uka.nenadic@manchester.ac.uk" />
```
I believe we can still represent `Event.contact` as CharField if only we separate multiple emails with a comma or other separator. Let me know if you have different opinion.

**Comment by maneesha** [comment] 2019-07-09 20:00
@pbanaszkiewicz Can we address this in the changes to the Workshop Request form we've been discussing?

**Comment by maneesha** [comment] 2021-12-15 11:35
I think we can close this because we do have comma separated values in that list, and we can give someone an explicit role if needed.

**Closed by maneesha** 2021-12-15 11:35 UTC
Labels: type: enhancement, status: needs feedback
